### ISSUE TITLE
Godot related changes associated with ImageTools module

### ISSUE THREAD

**Issue by Xrayez** [Xrayez/godot-imagetools#1]
A tracker to keep up with Godot changes related to the module (for consistency and/or compatibility).

- [ ] Rework PNG indexed driver: godotengine/godot#29874 (?)
- [ ] Use namespaces instead of underscore prefix for core bind classes godotengine/godot#26990.
    * ImageTools singleton replicates the same technique.

---

- [x] ~~Unexpose PNG indexed format loader/saver: godotengine/godot#2987~~
- [x] ~~Add HQ2X and the `Image.expand_2x_hq2x()` method: godotengine/godot#29587~~  implemented in 57b7c02.

**Comment by Xrayez** [comment]
Regarding HQ2X: the original library provides hq3x upscale algorithm as well which is worth checking out. https://github.com/brunexgeek/hqx

**Comment by Xrayez** [comment]
Can be transferred to Goost, see README.
