### ISSUE TITLE
ImageTools gd3 and gd4 changes

### ISSUE THREAD

**Issue by Xrayez** [Xrayez/godot-imagetools#3]
A tracker to keep the changes which are pending to be ported to `master-gd4` branch, or a list of commits/PRs which are exclusive to specific branches at the moment.

### Port `gd3` to `gd4`
- [x] 0a4eb7d87218983743a5999d22b5b0f6f2cca0a5
- [x] 57b7c02931db6b9a349ed21751f1db4820a17f17
- [x] 9bb7428700b0c6c058f1455d1e66e41879b10dde (remove Image.expand_2x_hq2x reference in 4.0).
- [ ] Implementing the ImageBlender class #5.

**Comment by Xrayez** [comment]
Can be transferred to Goost, see README.
