### ISSUE TITLE
Godot image processing related proposals which can be implemented in ImageTools module

### ISSUE THREAD

**Issue by Xrayez** [Xrayez/godot-imagetools#4]
A tracker to keep track of features which can be potentially implemented within a module.

- [x] Allow indexed mode pictures  godotengine/godot-proposals#429.
- [x] Save Images as PNG buffer godotengine/godot-proposals#859 (Implemented in Godot)
- [ ] Expose Load{image}FromBuffer for other formats (e.g. TGA, BMP) godotengine/godot-proposals#676.
- [ ] Add the ability to import and create palette indexed sprites from GIFs and APNGs godotengine/godot-proposals#475.
- [ ] Allow to import GIF files godotengine/godot#31831.

**Comment by Xrayez** [comment]
Can be transferred to Goost, see README.
